import { GymDetail } from "@/types/gyms/types";

export const MOCK_GYMS: GymDetail[] = [
  {
    id: "1",
    name: "더클라임 클라이밍 짐앤샵 강남점",
    thumbnail: "https://picsum.photos/seed/gym1/800/600",
    district: "강남구",
    address: "서울특별시 강남구 테헤란로 123",
    lat: 37.4979,
    lon: 127.0276,
    scrapCount: 2540,
    rating: 4.8,
    description:
      "국내 최대 규모의 볼더링 시설을 자랑하는 강남점입니다. 매주 새로운 문제가 세팅되며 초보자부터 상급자까지 즐길 수 있습니다.",
    images: [
      "https://picsum.photos/seed/g1-1/800/600",
      "https://picsum.photos/seed/g1-2/800/600",
    ],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
      { day: "공휴일", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-123-4567",
    facilities: ["샤워실", "스트레칭존", "초크대여", "암벽화대여", "주차가능"],
    tags: ["역세권", "대형암장", "난이도다양"],
    difficultySystem: {
      type: "color",
      levels: [
        "흰색",
        "노랑",
        "주황",
        "초록",
        "파랑",
        "빨강",
        "보라",
        "회색",
        "갈색",
        "검정",
      ],
    },
  },
  {
    id: "2",
    name: "게이트원 클라이밍",
    thumbnail: "https://picsum.photos/seed/gym2/800/600",
    district: "서초구",
    address: "서울특별시 서초구 서초대로 45",
    lat: 37.4912,
    lon: 127.0078,
    scrapCount: 1280,
    rating: 4.5,
    description:
      "지구력 트레이닝에 최적화된 암장입니다. 숙련된 강사진의 강습 프로그램이 준비되어 있습니다.",
    images: ["https://picsum.photos/seed/g2-1/800/600"],
    hours: [
      { day: "평일", time: "11:00 - 22:30", isClosed: false },
      { day: "주말", time: "10:00 - 19:00", isClosed: false },
      { day: "공휴일", time: "확인 필요", isClosed: true },
    ],
    contact: "02-987-6543",
    facilities: ["샤워실", "개인사물함", "강습프로그램"],
    tags: ["지구력중심", "고수많음", "강습맛집"],
    difficultySystem: {
      type: "color",
      levels: ["노랑", "분홍", "파랑", "빨강", "검정"],
    },
  },
  {
    id: "3",
    name: "픽스 볼더 역삼",
    thumbnail: "https://picsum.photos/seed/gym3/800/600",
    district: "강남구",
    address: "서울특별시 강남구 역삼로 88",
    lat: 37.5,
    lon: 127.0365,
    scrapCount: 850,
    rating: 4.3,
    description:
      "세련된 인테리어와 쾌적한 환기 시스템을 갖춘 신상 볼더링 파크입니다.",
    images: [
      "https://picsum.photos/seed/g3-1/800/600",
      "https://picsum.photos/seed/g3-2/800/600",
    ],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-555-4444",
    facilities: ["무료주차", "카페", "스트레칭존"],
    tags: ["신규오픈", "쾌적", "혼운가능"],
    difficultySystem: {
      type: "v-scale",
      levels: ["V0", "V1", "V2", "V3", "V4", "V5", "V6+"],
    },
  },
  {
    id: "4",
    name: "강남 클라이밍 센터",
    thumbnail: "https://picsum.photos/seed/gym4/800/600",
    district: "강남구",
    address: "서울특별시 강남구 논현로 10",
    lat: 37.485,
    lon: 127.042,
    scrapCount: 620,
    rating: 4.1,
    description:
      "오랜 전통을 가진 클라이밍 센터로, 실제 바위와 유사한 질감의 홀드가 특징입니다.",
    images: [],
    hours: [
      { day: "평일", time: "09:00 - 22:00", isClosed: false },
      { day: "토요일", time: "10:00 - 18:00", isClosed: false },
      { day: "일요일", time: "휴무", isClosed: true },
    ],
    contact: "02-444-5555",
    facilities: ["암벽화대여", "탈의실"],
    tags: ["클래식", "스트레칭존", "전통맛집"],
    difficultySystem: { type: "color", levels: ["빨강", "노랑", "파랑"] },
  },
  {
    id: "5",
    name: "양재 볼더파크",
    thumbnail: "https://picsum.photos/seed/gym5/800/600",
    district: "서초구",
    address: "서울특별시 서초구 양재동 200",
    lat: 37.475,
    lon: 127.04,
    scrapCount: 920,
    rating: 4.4,
    description:
      "양재천 근처에 위치하여 산책과 운동을 동시에 즐길 수 있는 숲세권 암장입니다.",
    images: ["https://picsum.photos/seed/g5-1/800/600"],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-111-9999",
    facilities: ["주차가능", "음료판매"],
    tags: ["주차편함", "친절한크루", "숲세권"],
    difficultySystem: {
      type: "color",
      levels: ["빨", "주", "노", "초", "파", "남", "보"],
    },
  },
  {
    id: "6",
    name: "청담 클라이밍 라운지",
    thumbnail: "https://picsum.photos/seed/gym6/800/600",
    district: "강남구",
    address: "서울특별시 강남구 압구정로 50",
    lat: 37.525,
    lon: 127.045,
    scrapCount: 430,
    rating: 4.6,
    description:
      "프라이빗하고 조용한 환경에서 클라이밍을 즐기고 싶은 분들을 위한 라운지형 암장입니다.",
    images: ["https://picsum.photos/seed/g6-1/800/600"],
    hours: [
      { day: "평일", time: "12:00 - 22:00", isClosed: false },
      { day: "주말", time: "10:00 - 18:00", isClosed: false },
    ],
    contact: "02-333-2222",
    facilities: ["단독샤워룸", "수건제공", "카페"],
    tags: ["프라이빗", "고급시설", "청담동"],
    difficultySystem: {
      type: "color",
      levels: ["레벨1", "레벨2", "레벨3", "레벨4", "레벨5"],
    },
  },
  {
    id: "7",
    name: "신사 볼더링",
    thumbnail: "https://picsum.photos/seed/gym7/800/600",
    district: "강남구",
    address: "서울특별시 강남구 도산대로 15",
    lat: 37.518,
    lon: 127.023,
    scrapCount: 770,
    rating: 4.2,
    description:
      "가로수길 핫플레이스에 위치하여 젊은 층이 많이 찾는 에너제틱한 공간입니다.",
    images: [],
    hours: [
      { day: "평일", time: "11:00 - 23:00", isClosed: false },
      { day: "주말", time: "11:00 - 21:00", isClosed: false },
    ],
    contact: "02-777-8888",
    facilities: ["탈의실", "무선인터넷"],
    tags: ["핫플레이스", "인스타감성", "가로수길"],
    difficultySystem: { type: "color", levels: ["초보", "중급", "고급"] },
  },
  {
    id: "8",
    name: "서초 V10",
    thumbnail: "https://picsum.photos/seed/gym8/800/600",
    district: "서초구",
    address: "서울특별시 서초구 반포동 33",
    lat: 37.505,
    lon: 127.005,
    scrapCount: 1100,
    rating: 4.7,
    description:
      "킬터보드와 문보드 등 다양한 트레이닝 보드를 갖춘 전문 볼더링 센터입니다.",
    images: [
      "https://picsum.photos/seed/g8-1/800/600",
      "https://picsum.photos/seed/g8-2/800/600",
    ],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-000-1111",
    facilities: ["샤워실", "킬터보드", "문보드"],
    tags: ["킬터보드", "문제맛집", "트레이닝"],
    difficultySystem: {
      type: "v-scale",
      levels: ["V0", "V2", "V4", "V6", "V8+"],
    },
  },
  {
    id: "9",
    name: "방배 클라임비",
    thumbnail: "https://picsum.photos/seed/gym9/800/600",
    district: "서초구",
    address: "서울특별시 서초구 방배로 99",
    lat: 37.482,
    lon: 126.993,
    scrapCount: 320,
    rating: 3.9,
    description:
      "방배동 주민들의 사랑을 받는 아담하고 가족 같은 분위기의 암장입니다.",
    images: [],
    hours: [
      { day: "평일", time: "13:00 - 22:30", isClosed: false },
      { day: "토요일", time: "12:00 - 18:00", isClosed: false },
      { day: "일요일", time: "정기휴무", isClosed: true },
    ],
    contact: "02-888-2222",
    facilities: ["암벽화대여", "정수기"],
    tags: ["로컬맛집", "조용한", "친절"],
    difficultySystem: { type: "color", levels: ["하늘", "바다", "우주"] },
  },
  {
    id: "10",
    name: "반포 자이언트",
    thumbnail: "https://picsum.photos/seed/gym10/800/600",
    district: "서초구",
    address: "서울특별시 서초구 잠원로 12",
    lat: 37.51,
    lon: 127.012,
    scrapCount: 550,
    rating: 4.0,
    description:
      "어린이 클라이밍 교실이 활성화되어 있어 온 가족이 함께 즐기기 좋습니다.",
    images: ["https://picsum.photos/seed/g10-1/800/600"],
    hours: [{ day: "매일", time: "10:00 - 21:00", isClosed: false }],
    contact: "02-555-1111",
    facilities: ["주차", "대기공간", "키즈존"],
    tags: ["어린이가능", "넓은대기공간", "가족운동"],
    difficultySystem: {
      type: "color",
      levels: ["흰색", "노랑", "주황", "초록"],
    },
  },
  {
    id: "11",
    name: "연남 볼더링 클럽",
    thumbnail: "https://picsum.photos/seed/gym11/800/600",
    district: "마포구",
    address: "서울특별시 마포구 연남로 1",
    lat: 37.562,
    lon: 126.924,
    scrapCount: 1850,
    rating: 4.9,
    description:
      "연트럴파크 옆 힙한 감성을 담은 암장입니다. 세련된 분위기에서 운동 후 연남동 맛집 투어를 즐기세요.",
    images: [
      "https://picsum.photos/seed/g11-1/800/600",
      "https://picsum.photos/seed/g11-2/800/600",
    ],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-111-2222",
    facilities: ["카페연계", "샤워실", "스트레칭존"],
    tags: ["분위기깡패", "데이트코스", "힙플레이스"],
    difficultySystem: {
      type: "color",
      levels: ["빨", "주", "노", "초", "파", "남", "보", "검"],
    },
  },
  {
    id: "12",
    name: "합정 볼더스",
    thumbnail: "https://picsum.photos/seed/gym12/800/600",
    district: "마포구",
    address: "서울특별시 마포구 독막로 5",
    lat: 37.548,
    lon: 126.912,
    scrapCount: 1450,
    rating: 4.7,
    description:
      "합정역 7번 출구 도보 1분 거리. 초보자를 위한 입문 강습이 매일 열립니다.",
    images: ["https://picsum.photos/seed/g12-1/800/600"],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 19:00", isClosed: false },
    ],
    contact: "02-333-5555",
    facilities: ["샤워실", "암벽화대여", "락커"],
    tags: ["초보친절", "역세권", "입문강습"],
    difficultySystem: {
      type: "color",
      levels: ["노랑", "분홍", "파랑", "빨강", "검정"],
    },
  },
  {
    id: "13",
    name: "홍대 클라이밍 이음",
    thumbnail: "https://picsum.photos/seed/gym13/800/600",
    district: "마포구",
    address: "서울특별시 마포구 와우산로 22",
    lat: 37.555,
    lon: 126.923,
    scrapCount: 980,
    rating: 4.4,
    description: "대학생 할인 혜택이 빵빵한 홍대 앞 활기찬 암장입니다.",
    images: [],
    hours: [
      { day: "평일", time: "11:00 - 23:00", isClosed: false },
      { day: "주말", time: "12:00 - 20:00", isClosed: false },
    ],
    contact: "02-444-6666",
    facilities: ["탈의실", "공용초크", "무선인터넷"],
    tags: ["가성비", "학생할인", "활기찬"],
    difficultySystem: {
      type: "color",
      levels: ["레벨1", "레벨2", "레벨3", "레벨4", "레벨5"],
    },
  },
  {
    id: "14",
    name: "망원 락트",
    thumbnail: "https://picsum.photos/seed/gym14/800/600",
    district: "마포구",
    address: "서울특별시 마포구 희우정로 30",
    lat: 37.55,
    lon: 126.902,
    scrapCount: 670,
    rating: 4.3,
    description:
      "망리단길 투어의 필수 코스. 커피 한 잔과 함께 즐거운 볼더링을 즐기세요.",
    images: ["https://picsum.photos/seed/g14-1/800/600"],
    hours: [
      { day: "평일", time: "12:00 - 22:30", isClosed: false },
      { day: "주말", time: "11:00 - 20:00", isClosed: false },
    ],
    contact: "02-777-0000",
    facilities: ["카페", "주차협소", "반려동물동반"],
    tags: ["망리단길", "커피맛집", "반려동물가능"],
    difficultySystem: { type: "color", levels: ["빨강", "파랑", "노랑"] },
  },
  {
    id: "15",
    name: "신촌 클라이머스",
    thumbnail: "https://picsum.photos/seed/gym15/800/600",
    district: "서대문구",
    address: "서울특별시 서대문구 신촌로 55",
    lat: 37.558,
    lon: 126.937,
    scrapCount: 540,
    rating: 4.1,
    description:
      "신촌역 인근 넓은 층고와 다양한 각도의 벽이 특징인 로컬 성지입니다.",
    images: [],
    hours: [
      { day: "평일", time: "10:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 19:00", isClosed: false },
    ],
    contact: "02-222-3333",
    facilities: ["샤워실", "스트레칭존"],
    tags: ["동호회환영", "넓음", "신촌역"],
    difficultySystem: {
      type: "color",
      levels: ["흰색", "노랑", "주황", "초록", "파랑", "빨강"],
    },
  },
  {
    id: "16",
    name: "이대 업사이드",
    thumbnail: "https://picsum.photos/seed/gym16/800/600",
    district: "서대문구",
    address: "서울특별시 서대문구 이화여대길 10",
    lat: 37.56,
    lon: 126.945,
    scrapCount: 420,
    rating: 4.0,
    description:
      "깔끔하고 여성 친절한 분위기. 입문자를 위한 맞춤형 코칭이 강점입니다.",
    images: ["https://picsum.photos/seed/g16-1/800/600"],
    hours: [
      { day: "평일", time: "11:00 - 22:00", isClosed: false },
      { day: "토요일", time: "12:00 - 18:00", isClosed: false },
      { day: "일요일", time: "정기휴무", isClosed: true },
    ],
    contact: "02-333-8888",
    facilities: ["깔끔한샤워실", "파우더룸"],
    tags: ["여성친절", "깔끔", "입문코칭"],
    difficultySystem: { type: "color", levels: ["핑크", "민트", "퍼플"] },
  },
  {
    id: "17",
    name: "공덕 볼더라운지",
    thumbnail: "https://picsum.photos/seed/gym17/800/600",
    district: "마포구",
    address: "서울특별시 마포구 마포대로 44",
    lat: 37.543,
    lon: 126.951,
    scrapCount: 890,
    rating: 4.5,
    description:
      "직장인들을 위한 야간 운영 서비스. 넓은 휴게 공간에서 편하게 쉬어가세요.",
    images: ["https://picsum.photos/seed/g17-1/800/600"],
    hours: [
      { day: "평일", time: "10:00 - 24:00", isClosed: false },
      { day: "주말", time: "10:00 - 21:00", isClosed: false },
    ],
    contact: "02-999-0000",
    facilities: ["주차가능", "대형락커", "야간운영"],
    tags: ["직장인모임", "야간운영", "공덕역"],
    difficultySystem: {
      type: "color",
      levels: ["레벨1", "레벨2", "레벨3", "레벨4", "레벨5", "레벨6"],
    },
  },
  {
    id: "18",
    name: "상암 클라이밍 월드",
    thumbnail: "https://picsum.photos/seed/gym18/800/600",
    district: "마포구",
    address: "서울특별시 마포구 월드컵로 100",
    lat: 37.578,
    lon: 126.892,
    scrapCount: 310,
    rating: 3.8,
    description:
      "국내 유수의 리드벽을 보유한 대형 암장입니다. 볼더링뿐만 아니라 리드 클라이밍 교육도 활발합니다.",
    images: ["https://picsum.photos/seed/g18-1/800/600"],
    hours: [
      { day: "평일", time: "10:00 - 22:00", isClosed: false },
      { day: "주말", time: "09:00 - 18:00", isClosed: false },
    ],
    contact: "02-444-1234",
    facilities: ["리드벽", "주차가능", "암벽장비판매"],
    tags: ["리드클라이밍", "고층고", "상암운동"],
    difficultySystem: {
      type: "v-scale",
      levels: ["V0", "V1", "V2", "V3", "V4"],
    },
  },
  {
    id: "19",
    name: "마포 홀드샵",
    thumbnail: "https://picsum.photos/seed/gym19/800/600",
    district: "마포구",
    address: "서울특별시 마포구 토정로 15",
    lat: 37.538,
    lon: 126.942,
    scrapCount: 460,
    rating: 4.2,
    description:
      "클라이밍 장비 편집샵과 암장이 결합된 이색 공간입니다. 장비 테스트 후 바로 구매가 가능합니다.",
    images: [],
    hours: [{ day: "매일", time: "11:00 - 21:00", isClosed: false }],
    contact: "02-555-6666",
    facilities: ["장비매장", "테스트존"],
    tags: ["장비쇼핑", "세팅맛집", "이색공간"],
    difficultySystem: {
      type: "color",
      levels: ["블루", "그린", "레드", "블랙"],
    },
  },
  {
    id: "20",
    name: "서강 볼더 그라운드",
    thumbnail: "https://picsum.photos/seed/gym20/800/600",
    district: "마포구",
    address: "서울특별시 마포구 백범로 10",
    lat: 37.55,
    lon: 126.935,
    scrapCount: 720,
    rating: 4.3,
    description:
      "작지만 강력한 문제들이 가득한 곳. 클라이밍 크루들의 모임 장소로 인기가 높습니다.",
    images: [
      "https://picsum.photos/seed/g20-1/800/600",
      "https://picsum.photos/seed/g20-2/800/600",
    ],
    hours: [
      { day: "평일", time: "12:00 - 23:00", isClosed: false },
      { day: "주말", time: "10:00 - 20:00", isClosed: false },
    ],
    contact: "02-777-1111",
    facilities: ["공용초크", "음료무료"],
    tags: ["매운맛문제", "크루모임", "서강대역"],
    difficultySystem: {
      type: "color",
      levels: ["레벨1", "레벨2", "레벨3", "레벨4", "레벨5"],
    },
  },

  // 21-30: 성수/광진/송파 (태그: #핫플, #고층고, #한강뷰)
  {
    id: "21",
    name: "더클라임 성수",
    district: "성동구",
    address: "아차산로 33",
    lat: 37.544,
    lon: 127.056,
    scrapCount: 3000,
    rating: 4.9,
    thumbnail: "https://picsum.photos/seed/21/800/600",
    description: "성수동 힙스터들의 성지",
    images: [],
    hours: [],
    contact: "",
    facilities: ["샤워실", "주차"],
    tags: ["고층고", "세팅맛집", "핫플"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "22",
    name: "피커스 뚝섬",
    district: "광진구",
    address: "뚝섬로 500",
    lat: 37.535,
    lon: 127.065,
    scrapCount: 1100,
    rating: 4.6,
    thumbnail: "https://picsum.photos/seed/22/800/600",
    description: "한강이 보이는 클라이밍",
    images: [],
    hours: [],
    contact: "",
    facilities: ["카페"],
    tags: ["한강뷰", "쾌적", "데이트"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "23",
    name: "건대 볼더홀릭",
    district: "광진구",
    address: "능동로 22",
    lat: 37.541,
    lon: 127.07,
    scrapCount: 950,
    rating: 4.4,
    thumbnail: "https://picsum.photos/seed/23/800/600",
    description: "대학생들의 아지트",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["가성비", "젊은분위기"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "24",
    name: "잠실 비블락",
    district: "송파구",
    address: "올림픽로 15",
    lat: 37.511,
    lon: 127.1,
    scrapCount: 1600,
    rating: 4.8,
    thumbnail: "https://picsum.photos/seed/24/800/600",
    description: "김자인 선수 운영 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차", "샤워실"],
    tags: ["전문강습", "송파대장"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "25",
    name: "문정 볼더팩토리",
    district: "송파구",
    address: "법원로 11",
    lat: 37.485,
    lon: 127.12,
    scrapCount: 580,
    rating: 4.2,
    thumbnail: "https://picsum.photos/seed/25/800/600",
    description: "직장인 운동 성지",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["직장인", "오운완"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "26",
    name: "성수 볼더 정션",
    district: "성동구",
    address: "성수이로 10",
    lat: 37.542,
    lon: 127.05,
    scrapCount: 1300,
    rating: 4.7,
    thumbnail: "https://picsum.photos/seed/26/800/600",
    description: "인더스트리얼 무드",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["세팅주기짧음", "힙플레이스"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "27",
    name: "광나루 클라이밍",
    district: "광진구",
    address: "천호대로 11",
    lat: 37.545,
    lon: 127.103,
    scrapCount: 290,
    rating: 3.7,
    thumbnail: "https://picsum.photos/seed/27/800/600",
    description: "조용히 운동하기 좋은 곳",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["조용한", "집중력"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "28",
    name: "방이 클라이밍존",
    district: "송파구",
    address: "위례성대로 5",
    lat: 37.515,
    lon: 127.115,
    scrapCount: 440,
    rating: 4.1,
    thumbnail: "https://picsum.photos/seed/28/800/600",
    description: "공원 산책 후 운동",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["올공옆", "가족동반"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "29",
    name: "석촌 호수 암장",
    district: "송파구",
    address: "석촌호수로 22",
    lat: 37.505,
    lon: 127.102,
    scrapCount: 820,
    rating: 4.5,
    thumbnail: "https://picsum.photos/seed/29/800/600",
    description: "뷰가 좋은 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["카페"],
    tags: ["뷰맛집", "데이트코스"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "30",
    name: "송파 웨이브",
    district: "송파구",
    address: "가락로 12",
    lat: 37.495,
    lon: 127.11,
    scrapCount: 390,
    rating: 4.0,
    thumbnail: "https://picsum.photos/seed/30/800/600",
    description: "파도가 치는 듯한 무브",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["다이나믹", "지구력"],
    difficultySystem: { type: "color", levels: [] },
  },

  // 31-40: 종로/중구/용산 (태그: #이색, #역사, #중심가)
  {
    id: "31",
    name: "피커스 종로",
    district: "종로구",
    address: "돈화문로 1",
    lat: 37.571,
    lon: 126.991,
    scrapCount: 2100,
    rating: 4.8,
    thumbnail: "https://picsum.photos/seed/31/800/600",
    description: "영화관 안의 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["샤워실", "영화관"],
    tags: ["이색경험", "영화관콜라보"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "32",
    name: "종로 클라이밍파크",
    district: "종로구",
    address: "인사동길 10",
    lat: 37.573,
    lon: 126.985,
    scrapCount: 750,
    rating: 4.2,
    thumbnail: "https://picsum.photos/seed/32/800/600",
    description: "전통 거리 속 운동",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["인사동", "관광객인기"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "33",
    name: "용산 클라이밍 정션",
    district: "용산구",
    address: "한강대로 10",
    lat: 37.53,
    lon: 126.97,
    scrapCount: 1350,
    rating: 4.7,
    thumbnail: "https://picsum.photos/seed/33/800/600",
    description: "교통의 요지",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["용산역", "교통편리"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "34",
    name: "한남 로프",
    district: "용산구",
    address: "독서당로 5",
    lat: 37.535,
    lon: 127.01,
    scrapCount: 520,
    rating: 4.4,
    thumbnail: "https://picsum.photos/seed/34/800/600",
    description: "세련된 한남동 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["단독샤워"],
    tags: ["한남동", "세련된"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "35",
    name: "을지로 힙클라임",
    district: "중구",
    address: "을지로 100",
    lat: 37.566,
    lon: 126.982,
    scrapCount: 880,
    rating: 4.5,
    thumbnail: "https://picsum.photos/seed/35/800/600",
    description: "을지로 감성",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["힙지로", "야간등반"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "36",
    name: "남산 릿지",
    district: "용산구",
    address: "소월로 2",
    lat: 37.55,
    lon: 126.988,
    scrapCount: 410,
    rating: 4.1,
    thumbnail: "https://picsum.photos/seed/36/800/600",
    description: "남산타워 뷰",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["뷰깡패", "남산타워"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "37",
    name: "동대문 벽커스",
    district: "동대문구",
    address: "장한로 5",
    lat: 37.575,
    lon: 127.042,
    scrapCount: 630,
    rating: 4.0,
    thumbnail: "https://picsum.photos/seed/37/800/600",
    description: "동대문 대형 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["넓은공간", "대중교통"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "38",
    name: "서대문 볼더가든",
    district: "서대문구",
    address: "충정로 10",
    lat: 37.56,
    lon: 126.963,
    scrapCount: 340,
    rating: 3.9,
    thumbnail: "https://picsum.photos/seed/38/800/600",
    description: "정원 같은 편안함",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["아늑한", "초보추천"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "39",
    name: "명동 클라임비",
    district: "중구",
    address: "명동길 3",
    lat: 37.563,
    lon: 126.984,
    scrapCount: 290,
    rating: 3.8,
    thumbnail: "https://picsum.photos/seed/39/800/600",
    description: "쇼핑하고 운동하고",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["명동역", "쇼핑"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "40",
    name: "경복궁 락원",
    district: "종로구",
    address: "효자로 1",
    lat: 37.578,
    lon: 126.975,
    scrapCount: 560,
    rating: 4.3,
    thumbnail: "https://picsum.photos/seed/40/800/600",
    description: "궁 근처 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["궁세권", "외국인인기"],
    difficultySystem: { type: "color", levels: [] },
  },

  // 41-50: 영등포/관악/구로 (태그: #퇴근후, #가성비, #커뮤니티)
  {
    id: "41",
    name: "더클라임 신림",
    district: "관악구",
    address: "신림로 33",
    lat: 37.484,
    lon: 126.929,
    scrapCount: 1950,
    rating: 4.7,
    thumbnail: "https://picsum.photos/seed/41/800/600",
    description: "신림 핫플",
    images: [],
    hours: [],
    contact: "",
    facilities: ["샤워실"],
    tags: ["신림역", "사람많음"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "42",
    name: "당산 볼더라이프",
    district: "영등포구",
    address: "당산로 2",
    lat: 37.534,
    lon: 126.902,
    scrapCount: 730,
    rating: 4.3,
    thumbnail: "https://picsum.photos/seed/42/800/600",
    description: "쾌적한 당산 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["쾌적함", "친절"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "43",
    name: "문래 락스테이션",
    district: "영등포구",
    address: "경인로 10",
    lat: 37.512,
    lon: 126.895,
    scrapCount: 1150,
    rating: 4.6,
    thumbnail: "https://picsum.photos/seed/43/800/600",
    description: "문래 창작촌 감성",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["문래창작촌", "예술"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "44",
    name: "영등포 클라임어스",
    district: "영등포구",
    address: "영신로 40",
    lat: 37.52,
    lon: 126.908,
    scrapCount: 640,
    rating: 4.2,
    thumbnail: "https://picsum.photos/seed/44/800/600",
    description: "쇼핑몰 근처",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["타임스퀘어", "주차편함"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "45",
    name: "구로 볼더링 랩",
    district: "구로구",
    address: "디지털로 2",
    lat: 37.485,
    lon: 126.89,
    scrapCount: 520,
    rating: 4.1,
    thumbnail: "https://picsum.photos/seed/45/800/600",
    description: "IT 단지 숨은 고수",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["고수전용", "킬터보드"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "46",
    name: "샤로수 클라이밍",
    district: "관악구",
    address: "관악로 1",
    lat: 37.478,
    lon: 126.952,
    scrapCount: 910,
    rating: 4.6,
    thumbnail: "https://picsum.photos/seed/46/800/600",
    description: "샤로수길 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: ["카페"],
    tags: ["샤로수길", "분위기굿"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "47",
    name: "가산 암벽원",
    district: "금천구",
    address: "가산로 5",
    lat: 37.48,
    lon: 126.882,
    scrapCount: 380,
    rating: 4.0,
    thumbnail: "https://picsum.photos/seed/47/800/600",
    description: "가성비 연습장",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["가성비", "연습용"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "48",
    name: "보라매 릿지",
    district: "동작구",
    address: "보라매로 2",
    lat: 37.492,
    lon: 126.92,
    scrapCount: 470,
    rating: 4.3,
    thumbnail: "https://picsum.photos/seed/48/800/600",
    description: "보라매공원 뷰",
    images: [],
    hours: [],
    contact: "",
    facilities: ["주차"],
    tags: ["공원뷰", "가족운동"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "49",
    name: "대림 볼더링샵",
    district: "구로구",
    address: "대림로 3",
    lat: 37.49,
    lon: 126.895,
    scrapCount: 250,
    rating: 3.5,
    thumbnail: "https://picsum.photos/seed/49/800/600",
    description: "로컬 전문 암장",
    images: [],
    hours: [],
    contact: "",
    facilities: [],
    tags: ["로컬", "매운맛"],
    difficultySystem: { type: "color", levels: [] },
  },
  {
    id: "50",
    name: "영등포 웨이브",
    district: "영등포구",
    address: "국회대로 10",
    lat: 37.528,
    lon: 126.915,
    scrapCount: 690,
    rating: 4.4,
    thumbnail: "https://picsum.photos/seed/50/800/600",
    description: "여의도 인근",
    images: [],
    hours: [],
    contact: "",
    facilities: ["샤워실"],
    tags: ["여의도", "직장인동호회"],
    difficultySystem: { type: "color", levels: [] },
  },
];
